---
-
  name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

-
  name: Start runner service
  ansible.builtin.systemd:
    name: "{{ _git_runner_service_file | basename }}"
    state: started
    enabled: true
  when: _git_runner_service_file is defined
