---
-
  name: Restart github-actions-runner
  ansible.builtin.systemd:
    name: "{{ git_runner_service_name }}"
    state: restarted
    daemon_reload: true
  when: git_runner_service_enabled

-
  name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
