---
-
  name: Start runner service
  ansible.builtin.systemd:
    # TODO:  get this from the svc.sh script?
    # Organization:  MyOrg > actions.runner.MyOrg.my-runner-test
    # Repository:  MyOrg/MyRepo > actions.runner.MyOrg-MyRepo.my-runner-test
    name: "actions.runner.{{ git_runner_org if git_runner_org != '' else git_runner_repo | replace('/', '-') }}.{{ git_runner_name }}.service"
    state: started
    daemon_reload: true

-
  name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
